#enable hot swapping
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nowcoder_sql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
#date format
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
#logging
logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.example: trace
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true